@echo off

fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)

rem Windows apps

>nul 2>&1 (
	PowerShell -Command "Get-AppxPackage *3DBuilder* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *ActiproSoftwareLLC* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *AdobeSystemsIncorporated.AdobePhotoshopExpress* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *AV1VideoExtension* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *bing* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *BingNews* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *BingWeather* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *CandyCrush* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *CommsPhone* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *ConnectivityStore* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Drawboard PDF* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Duolingo* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *EclipseManager* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Facebook* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Flipboard* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *GetHelp* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Getstarted* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *HEIFImageExtension* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *HiddenCityMysteryofShadows* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *HuluLLC.HuluPlus* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *king.com.FarmHeroesSaga* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Netflix* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *NVIDIACorp.NVIDIAControlPanel* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *OneDriveSync* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *OneNote* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Paint* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Pandora* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *people* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *photos* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Plex* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *PowerAutomateDesktop* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *ROBLOXCORPORATION.ROBLOX* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *SkypeApp* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *solit* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Spotify* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *SpotifyAB.SpotifyMusic* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Sway* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Teams* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Todos* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Twitter* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WebpImageExtension* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Windows.Photos* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsAlarms* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsCalculator* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsCamera* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *windowscommunicationsapps* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsFeedbackHub* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsMaps* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsNotepad* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsPhone* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *WindowsSoundRecorder* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *Wunderlist* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *YourPhone* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *zune* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *ZuneMusic* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage *ZuneVideo* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.549981C3F5F10* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.BingNews* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.BingWeather* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.DesktopAppInstaller* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.GetHelp* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Getstarted* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.HEIFImageExtension* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Messaging* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Microsoft3DViewer* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.MicrosoftEdge.Stable* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.MicrosoftOfficeHub* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.MicrosoftSolitaireCollection* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.MicrosoftStickyNotes* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.MixedReality.Portal* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.MSPaint* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Office.OneNote* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.People* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Print3D* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.ScreenSketch* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.SkypeApp* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.StorePurchaseApp* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.VCLibs.140.00* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.VP9VideoExtensions* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Wallet* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WebMediaExtensions* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WebpImageExtension* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Windows.Photos* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WindowsAlarms* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WindowsCalculator* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WindowsCamera* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.windowscommunicationsapps* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WindowsFeedbackHub* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WindowsMaps* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WindowsSoundRecorder* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.WindowsStore* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.Xbox.TCUI* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.XboxApp* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.XboxGameOverlay* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.XboxGamingOverlay* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.XboxIdentityProvider* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.XboxSpeechToTextOverlay* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.YourPhone* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.ZuneMusic* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage Microsoft.ZuneVideo* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage MicrosoftEdge* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage MicrosoftOfficeHub* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage MicrosoftSolitaireCollection* | Remove-AppxPackage"
	PowerShell -Command "Get-AppxPackage MicrosoftStickyNotes* | Remove-AppxPackage"
)

echo Done&>nul pause